name: inception

# Build containers
services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    networks:
      - inception-net
    volumes:
      - mariadb:/var/lib/mysql
  
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    networks:
      - inception-net
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
  
  nginx:
    container_name: nginx
    build:
      context: requiremets/nginx
    networks:
      - inception-net
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  # Create network
  networks:
    inception:
      name: inception-net
  
  # Create volumes
  volumes:
    mariadb:
      driver_opts:
        o: bind
        type: none
        device: /home/hepiment/data/mariadb
    wordpress:
      driver_opts:
        o: bind
        type: none
        device: /home/hepiment/data/wordpress

